FROM registry.access.redhat.com/ubi9/ubi-init:latest  as getter

WORKDIR /tmp/

RUN dnf install -y git python3 python

# Prepare next Step
COPY ../custom-util/get-powerline-shell.sh .


# Install custom util
RUN ./get-powerline-shell.sh


FROM registry.fedoraproject.org/fedora-toolbox:39

ARG NAME=joshua-base
ARG TYPE=base
ARG BIN_DIR=/usr/local/bin


LABEL name="$NAME" \
    type="base" \
    summary="joshua base container" \
    maintainer="ed1us3r" \
    author="ed1us3r"

ENV EDITOR=nvim \
    CONTAINER_ENV="true" \
    container_env="true" \
    image_name="$NAME" \
    image_type="$TYPE" \
    image_summary="joshua base container" \
    image_maintainer="ed1us3r" \
    image_author="ed1us3r"

# Install packages
RUN  yum -y upgrade \
  && yum -y install \
  git \
  nnn \
  lsd \
  ripgrep \
  fd-find \
  && yum clean all


# Copy Bins
COPY --from=getter --chown=root:root ${BIN_DIR}/powerline-shell ${BIN_DIR}/powerline-shell
