FROM registry.access.redhat.com/ubi9/ubi-init:latest  as getter

WORKDIR /tmp/

RUN dnf install -y git

# Prepare next Step
COPY ../custom-util/* .


# Install custom util
RUN ./get-cosign.sh && ./get-kubectl.sh


FROM registry.access.redhat.com/ubi9/ubi:latest

ARG NAME=joshua-base
ARG TYPE=base
ARG BIN_DIR=/usr/local/bin


LABEL name="$NAME" \
    type="k8s" \
    summary="joshua kubernetes engineering container" \
    maintainer="ed1us3r" \
    author="ed1us3r"

ENV EDITOR=nvim \
    CONTAINER_ENV="true" \
    container_env="true" \
    image_name="$NAME" \
    image_type="$TYPE" \
    image_summary="joshua kubernetes engineering container" \
    image_maintainer="ed1us3r" \
    image_author="ed1us3r"

# Install packages
RUN  yum -y upgrade \
  && yum -y install \
  git \
  nnn \
  lsd \
  ripgrep \
  fd-find \
  neovim \
  && yum clean all


# Copy Binaries from getter

COPY --from=getter --chown=root:root /usr/bin/cosign-linux-amd64 ${BIN_DIR}//cosign-linux-amd64

COPY --from=getter --chown=root:root /root/.krew/bin/kubectl* ${BIN_DIR}/kubectl-plugins/

COPY --from=getter --chown=root:root ${BIN_DIR}/kubectl ${BIN_DIR}/kubectl

# Create some Sym Links
RUN ln -s ${BIN_DIR}/cosign-linux-amd64 ${BIN_DIR}/cosign \
    && ln -s ${BIN_DIR}/kubectl-plugins/kubectl-krew ${BIN_DIR}/krew \
    && ln -s ${BIN_DIR}/kubectl-plugins/kubectl-cnpg ${BIN_DIR}/kubectl-cnpg \
    && ln -s ${BIN_DIR}/kubectl-plugins/kubectl-tree ${BIN_DIR}/kubectl-tree \ 
    && ln -s ${BIN_DIR}/kubectl-plugins/kubectl-flame ${BIN_DIR}/kubectl-flame 
